### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by osvaldoM** [osvaldoM/devnotes#2]
- [ ] [new languages for emprego]( https://github.com/uxmz/emprego/issues/865)
- [ ] [Simplify template files]( https://github.com/uxmz/emprego/issues/903)
- [ ] [Add noindex,nofollow for dev]( https://github.com/uxmz/emprego/issues/888)
- [ ] [Notify recruiter on account expiry]( https://github.com/uxmz/emprego/issues/838)
- [ ] [Add resend activation email on mobile]( https://github.com/uxmz/emprego/issues/887)
- [ ] [Send email to recruiter after account creation]( https://github.com/uxmz/emprego/issues/897)
- [ ] [Add google ads]( https://github.com/uxmz/emprego/issues/953)
- [ ] [Update WordPress to 4.9]( https://github.com/uxmz/emprego/issues/891)
- [ ] [Change pub to text]( https://github.com/uxmz/emprego/issues/938)
- [ ] [Notify recruiter on new candidate  ]( https://github.com/uxmz/emprego/issues/839)
- [ ] [Add push state in login page.]( https://github.com/uxmz/emprego/issues/900)
- [ ] [Add tag pages in WP]( https://github.com/uxmz/emprego/issues/894)
- [ ] [Mobile signup]( https://github.com/uxmz/emprego/issues/880)
